name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - name: Install dependencies
        run: yarn install
      - name: Run lint check
        run: yarn lint
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - name: Install dependencies
        run: yarn install
      - name: Run format
        run: yarn format
      - name: Check diff
        run: git diff --exit-code

